development:
  adapter: postgresql
  encoding: unicode
  database: campaigns_development
  port: 5432
  pool: 5
  host: localhost
  username: postgres
  password: '91141'

test:
  adapter: postgresql
  encoding: unicode
  database: campaigns_test
  pool: 5
  port: 5432
  host: localhost
  username: postgres
  password: '91141'

production:
  adapter: postgresql
  encoding: unicode
  database: Campaigns_production
  pool: 5
  username: postgres
  password: '91141'
